[workspace]
members = ["week1/week1", "week2", "week3", "week4", "week5", "week6", "week7", "week8"]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
dmoj = "0.1.5"
rand = "0.8.5"
